// GET_ - get запрос к апи
// POST_ - post запрос к апи

// PUT_ - изменить state инфой из апи запроса
// SET_ - изменить state без апи запросов
// REPLACE_ - заменить state
// RESET_ - обнулить state

// SHOW_ - показать модальное окно
// HIDE_ - скрыть модальное окно

export const AUTO_LOGIN = "APP/AUTO_LOGIN";
export const POST_LOGIN_PHONE = "APP/POST_LOGIN_PHONE";
export const POST_LOGIN_SMS = "APP/POST_LOGIN_SMS";
export const PUT_LOGIN_SMS_RESPONSE = "APP/PUT_LOGIN_SMS_RESPONSE";
export const RESET_LOGIN_SMS_RESPONSE = "APP/RESET_LOGIN_SMS_RESPONSE";
export const SET_IS_AUTH = "APP/SET_IS_AUTH";

export const POST_DEVICE_TOKEN = "APP/POST_DEVICE_TOKEN";

export const GET_SLIDER = "APP/GET_SLIDER";
export const PUT_SLIDER = "APP/PUT_SLIDER";

export const SHOW_MODAL_SLIDER_TEXT = "APP/SHOW_MODAL_SLIDER_TEXT";
export const HIDE_MODAL_SLIDER_TEXT = "APP/HIDE_MODAL_SLIDER_TEXT";
export const SET_MODAL_SLIDER_TEXT = "APP/SET_MODAL_SLIDER_TEXT";

export const SHOW_FULLSCREEN_LOADING = "MODAL/SHOW_FULLSCREEN_LOADING";
export const HIDE_FULLSCREEN_LOADING = "MODAL/HIDE_FULLSCREEN_LOADING";

export const GET_CATALOG = "CATALOG/GET_CATALOG";
export const PUT_CATALOG = "CATALOG/PUT_CATALOG";

export const SHOW_MODAL_PRODUCT = "CATALOG/SHOW_MODAL_PRODUCT";
export const HIDE_MODAL_PRODUCT = "CATALOG/HIDE_MODAL_PRODUCT";
export const SET_MODAL_PRODUCT = "CATALOG/SET_MODAL_PRODUCT";

export const SHOW_MODAL_FILTER = "FILTER/SHOW_MODAL_FILTER";
export const HIDE_MODAL_FILTER = "FILTER/HIDE_MODAL_FILTER";

export const SET_FILTER_LIST = "FILTER/SET_FILTER_LIST";
export const SET_FILTER_CATEGORIES = "FILTER/SET_FILTER_CATEGORIES";
export const SET_FILTER_ORDER = "FILTER/SET_FILTER_ORDER";
export const RESET_FILTER = "FILTER/RESET_FILTER";

export const GET_HISTORY = "HISTORY/GET_HISTORY";
export const PUT_HISTORY = "HISTORY/PUT_HISTORY";
export const RESET_HISTORY = "HISTORY/RESET_HISTORY";

export const ADD_TO_QUEUE = "QUEUE/ADD_TO_QUEUE"; // prefix?
export const REPLACE_QUEUE = "QUEUE/REPLACE_QUEUE";
export const RELEASE_QUEUE = "QUEUE/RELEASE_QUEUE"; // prefix?

export const GET_BASKET = "ORDER/GET_BASKET";
export const PUT_BASKET = "ORDER/PUT_BASKET";

export const POST_ADD_PROMOCODE = "ORDER/POST_ADD_PROMOCODE";
export const POST_REMOVE_PROMOCODE = "ORDER/POST_REMOVE_PROMOCODE";

export const GET_DATETIME = "ORDER/GET_DATETIME";
export const PUT_DATETIME = "ORDER/PUT_DATETIME";

export const SET_ORDER = "ORDER/SET_ORDER";
export const SET_ORDER_DATE = "ORDER/SET_ORDER_DATE";
export const SET_ORDER_TIME = "ORDER/SET_ORDER_TIME";
export const SET_ORDER_PAYMENT = "ORDER/SET_ORDER_PAYMENT";
export const POST_ORDER = "ORDER/POST_ORDER";

export const POST_CREATE_PAYMENT = "PAYMENT/POST_CREATE_PAYMENT";
export const POST_CREATE_PAYMENT_ALIF = "PAYMENT/POST_CREATE_PAYMENT_ALIF";
export const POST_CHECK_PAYMENT = "PAYMENT/POST_CHECK_PAYMENT";
export const SET_PAYMENT_LINK = "PAYMENT/SET_PAYMENT_LINK";
export const SET_PAYMENT_ORDER_ID = "PAYMENT/SET_PAYMENT_ORDER_ID";
export const SET_DATA_ALIF = "PAYMENT/SET_DATA_ALIF";

export const SHOW_MODAL_ORDER_DATE = "ORDER/SHOW_MODAL_ORDER_DATE";
export const HIDE_MODAL_ORDER_DATE = "ORDER/HIDE_MODAL_ORDER_DATE";
export const SHOW_MODAL_ORDER_TIME = "ORDER/SHOW_MODAL_ORDER_TIME";
export const HIDE_MODAL_ORDER_TIME = "ORDER/HIDE_MODAL_ORDER_TIME";

export const SHOW_MODAL_LOGIN = "MODAL/SHOW_MODAL_LOGIN";
export const HIDE_MODAL_LOGIN = "MODAL/HIDE_MODAL_LOGIN";
export const SET_MODAL_LOGIN_SHOWN_AT_ORDER =
  "MODAL/SET_MODAL_LOGIN_SHOWN_AT_ORDER";

export const SHOW_MODAL_PICKER = "MODAL/SHOW_MODAL_PICKER";
export const HIDE_MODAL_PICKER = "MODAL/HIDE_MODAL_PICKER";
export const SET_MODAL_PICKER_DATA = "MODAL/SET_MODAL_PICKER_DATA";
